spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysqlUrl}
    username: ${username}
    password: ${password}
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
